version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:11
    restart: always
    ports:
      - "5444:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  db_data:
