version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:11
    restart: always
    ports:
      - "5444:5432"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    container_name: backend
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  db_data:

networks:
  app-network:
