env: "local" # local / dev / prod

http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s

storage:
  host: "localhost"
  port: "5432"
  database: "avito-slug"
  username: "postgres"
  password: "root"
