env: "prod" # local / dev / prod

http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s

storage:
  host: "postgres" # container name
  port: "5432"
  database: "avito_db"
  username: "postgres"
  password: "root"
